import type { Block, AnimationTheme } from '@/lib/stores/builder-store'
import { allAnimations } from '@/data/animations'
import { COMPONENT_NAME_MAP } from './prompt-exporter'

const THEME_CONFIG: Record<
  AnimationTheme,
  { easing: string; duration: string }
> = {
  minimal: {
    easing: 'var(--ease-out-expo)',
    duration: 'var(--duration-fast)',
  },
  bold: {
    easing: 'var(--ease-spring)',
    duration: 'var(--duration-medium)',
  },
  editorial: {
    easing: 'var(--ease-out-expo)',
    duration: 'var(--duration-slow)',
  },
  luxury: {
    easing: 'var(--ease-in-out-quart)',
    duration: 'var(--duration-dramatic)',
  },
}

function propsToJSX(props: Record<string, unknown>): string {
  return Object.entries(props)
    .filter(([, v]) => v !== undefined && v !== null && v !== '')
    .map(([key, value]) => {
      if (typeof value === 'string') return `${key}="${value}"`
      if (typeof value === 'boolean') return value ? key : `${key}={false}`
      return `${key}={${JSON.stringify(value)}}`
    })
    .join(' ')
}

function getChildrenJSX(componentId: string): string | null {
  const childrenMap: Record<string, string> = {
    'hero-sequence': `
        <h1 className="text-5xl font-bold">Welcome</h1>
        <p className="text-xl text-gray-400">Your next-level animated experience.</p>
        <button className="rounded-lg bg-[--color-accent] px-6 py-3 font-semibold text-black">
          Get Started
        </button>`,
    'magnetic-button': `
        <span className="inline-block rounded-full bg-[--color-accent] px-8 py-4 font-semibold text-black">
          Click me
        </span>`,
    'parallax-image': `
        <div className="h-64 rounded-xl bg-gradient-to-br from-blue-500 to-purple-600" />`,
    'stagger-grid-reveal': `
        {Array.from({ length: 6 }, (_, i) => (
          <div key={i} className="rounded-xl border border-white/10 bg-white/5 p-6 text-center">
            Card {i + 1}
          </div>
        ))}`,
    'cursor-trail': `
        <div className="flex h-64 items-center justify-center text-gray-400">
          Move your cursor here
        </div>`,
    'page-transition': `
        <div className="p-8 text-center">Page Content</div>`,
    'liquid-hover': `
        <div className="p-4 text-center font-semibold text-white">Hover me</div>`,
    'tilt-3d-card': `
        <div className="rounded-xl border border-white/10 bg-white/5 p-6">
          <h3 className="text-lg font-semibold text-white">Interactive Card</h3>
          <p className="text-sm text-gray-400">Move your mouse over me</p>
        </div>`,
    'horizontal-scroll': `
        <div className="flex h-full items-center justify-center bg-[#1a1a2e] text-xl font-semibold text-white">Panel 1</div>
        <div className="flex h-full items-center justify-center bg-[#16213e] text-xl font-semibold text-white">Panel 2</div>
        <div className="flex h-full items-center justify-center bg-[#0f3460] text-xl font-semibold text-white">Panel 3</div>`,
    'pin-section': `
        <div className="flex h-full items-center justify-center">
          <h2 className="text-3xl font-bold text-white">Pinned Content</h2>
        </div>`,
    'glow-border': `
        <div className="p-5 text-center text-white">Hover for glow</div>`,
    'stagger-list': `
        {Array.from({ length: 5 }, (_, i) => (
          <div key={i} className="rounded-lg border border-white/10 bg-white/5 p-3 text-sm">
            List item {i + 1}
          </div>
        ))}`,
  }
  return childrenMap[componentId] ?? null
}

export function exportToNextJS(
  blocks: Block[],
  theme: AnimationTheme,
): string {
  const usedIds = [...new Set(blocks.map((b) => b.componentId))]
  const componentNames = usedIds
    .map((id) => COMPONENT_NAME_MAP[id])
    .filter(Boolean)

  const themeConfig = THEME_CONFIG[theme]
  const now = new Date().toISOString()

  const lines: string[] = []

  // Header comment
  lines.push(
    `// Generated by Animation Craft Studio`,
    `// Theme: ${theme} | Blocks: ${blocks.length} | Generated: ${now}`,
    ``,
    `'use client'`,
    ``,
  )

  // Imports
  if (componentNames.length > 0) {
    lines.push(
      `import {`,
      `  ${componentNames.join(',\n  ')},`,
      `} from '@/components/animations'`,
      ``,
    )
  }

  // Theme constants
  lines.push(
    `const ANIMATION_THEME = {`,
    `  easing: '${themeConfig.easing}',`,
    `  duration: '${themeConfig.duration}',`,
    `}`,
    ``,
  )

  // Page component
  lines.push(`export default function GeneratedPage() {`, `  return (`, `    <main>`)

  // Each block as a section
  const sortedBlocks = [...blocks].sort((a, b) => a.order - b.order)

  for (const block of sortedBlocks) {
    const name = COMPONENT_NAME_MAP[block.componentId]
    if (!name) continue

    const entry = allAnimations.find((e) => e.id === block.componentId)
    const propsStr = propsToJSX(block.props)
    const delayStyle =
      block.animationConfig.delay > 0
        ? ` style={{ animationDelay: '${block.animationConfig.delay}ms' }}`
        : ''
    const disabledAttr = block.animationConfig.disabled
      ? ' data-animation="disabled"'
      : ''

    lines.push(
      `      {/* ${entry?.name.en ?? name} */}`,
      `      <section${delayStyle}${disabledAttr}>`,
    )

    const children = getChildrenJSX(block.componentId)
    if (children) {
      lines.push(
        `        <${name}${propsStr ? ' ' + propsStr : ''}>`,
        `  ${children}`,
        `        </${name}>`,
      )
    } else {
      lines.push(
        `        <${name}${propsStr ? ' ' + propsStr : ''} />`,
      )
    }

    lines.push(`      </section>`, ``)
  }

  lines.push(`    </main>`, `  )`, `}`, ``)

  return lines.join('\n')
}
