export const DEFAULT_PROPS: Record<string, Record<string, unknown>> = {
  'hero-sequence': { delay: 0 },
  'text-split-reveal-up': { text: 'Animation Craft Studio', delay: 0, as: 'h1' },
  'text-scramble': { text: 'HOVER ME', trigger: 'mount' },
  'magnetic-button': { strength: 0.4 },
  'parallax-image': { speed: 0.3, direction: 'up' },
  'stagger-grid-reveal': { staggerDelay: 0.08 },
  'cursor-trail': { color: '#a0ff60', size: 8, count: 8 },
  'page-transition': {},
  'floating-particles': { count: 15, color: '#a0ff60', size: 3 },
  'glitch-text': { text: 'GLITCH', active: true },
  'liquid-hover': { fillColor: '#a0ff60' },
  'tilt-3d-card': { maxTilt: 15 },
  'counter-up': { target: 2500, suffix: '+', prefix: '', duration: 2 },
  'horizontal-scroll': {},
  'pin-section': {},
  'typewriter-text': {
    text: 'Building the future of web animation.',
    speed: 60,
    cursor: true,
  },
  'glow-border': { glowColor: '#a0ff60', borderRadius: '12px' },
  'stagger-list': { staggerDelay: 0.1, direction: 'up' },
  'splash-screen': { duration: 2000 },
  'morphing-shape': { color: '#a0ff60', animate: true },
}
